/* eslint-disable prettier/prettier */
import {faker} from '@faker-js/faker';

export const bookingData = [
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '60-636-6045',
    order_date: '21/11/2022',
    check_in: '16/08/2023',
    check_out: '10/09/2023',
    special_request: 'San Bernardino International Airport',
    room_type: 'Single Bed',
    room_number: 127,
    status: 'In Progress',
    price: 101,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '70-254-7579',
    order_date: '11/11/2022',
    check_in: '23/05/2023',
    check_out: '11/07/2023',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 139,
    status: 'Available',
    price: 450,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '48-718-0097',
    order_date: '15/04/2022',
    check_in: '21/02/2023',
    check_out: '25/02/2023',
    special_request: 'South Bend Regional Airport',
    room_type: 'Single Bed',
    room_number: 113,
    status: 'Occupied',
    price: 158,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '74-212-9482',
    order_date: '10/06/2022',
    check_in: '27/09/2023',
    check_out: '28/09/2023',
    special_request: 'Area De Material Airport',
    room_type: 'Single Bed',
    room_number: 118,
    status: 'Occupied',
    price: 258,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '76-100-9135',
    order_date: '11/11/2022',
    check_in: '22/08/2023',
    check_out: '01/01/2024',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 106,
    status: 'Occupied',
    price: 785,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '77-630-3254',
    order_date: '26/08/2022',
    check_in: '07/05/2023',
    check_out: '11/01/2024',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 248,
    status: 'In Progress',
    price: 125,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '07-056-8615',
    order_date: '24/09/2022',
    check_in: '13/11/2023',
    check_out: '23/11/2023',
    special_request: 'General Guadalupe Victoria International Airport',
    room_type: 'Single Bed',
    room_number: 7,
    status: 'In Progress',
    price: 185,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '99-127-6277',
    order_date: '15/07/2022',
    check_in: '12/05/2022',
    check_out: '03/02/2024',
    special_request: 'José Martí International Airport',
    room_type: 'Single Bed',
    room_number: 214,
    status: 'Occupied',
    price: 652,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '47-137-4044',
    order_date: '31/08/2022',
    check_in: '30/08/2023',
    check_out: '02/06/2023',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 228,
    status: 'Occupied',
    price: 489,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '26-238-2724',
    order_date: '24/10/2022',
    check_in: '08/05/2023',
    check_out: '04/06/2023',
    special_request: 'Anfa Airport',
    room_type: 'Single Bed',
    room_number: 144,
    status: 'Occupied',
    price: 1368,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '42-700-3629',
    order_date: '15/06/2022',
    check_in: '05/02/2023',
    check_out: '05/03/2023',
    special_request: 'Raroia Airport',
    room_type: 'Single Bed',
    room_number: 124,
    status: 'Occupied',
    price: 262,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '64-944-1863',
    order_date: '21/10/2022',
    check_in: '12/05/2023',
    check_out: '02/06/2023',
    special_request: 'Votuporanga Airport',
    room_type: 'Single Bed',
    room_number: 134,
    status: 'Occupied',
    price: 987,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '45-225-2209',
    order_date: '05/08/2022',
    check_in: '17/04/2023',
    check_out: '18/11/2023',
    special_request: 'Sumbe Airport',
    room_type: 'Single Bed',
    room_number: 66,
    status: 'Occupied',
    price: 1875,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '28-035-5284',
    order_date: '05/11/2022',
    check_in: '05/12/2023',
    check_out: '29/12/2023',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 102,
    status: 'Occupied',
    price: 1851,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '95-290-6881',
    order_date: '30/11/2022',
    check_in: '29/03/2023',
    check_out: '22/09/2023',
    special_request: 'Dix-Sept Rosado Airport',
    room_type: 'Single Bed',
    room_number: 221,
    status: 'In Progress',
    price: 365,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '50-133-9268',
    order_date: '11/12/2022',
    check_in: '11/07/2023',
    check_out: '20/01/2024',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 249,
    status: 'Occupied',
    price: 2587,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '36-003-9578',
    order_date: '16/07/2022',
    check_in: '29/05/2023',
    check_out: '30/05/2023',
    special_request: 'Torrington Municipal Airport',
    room_type: 'Single Bed',
    room_number: 198,
    status: 'Occupied',
    price: 101,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '38-817-7057',
    order_date: '06/01/2023',
    check_in: '10/07/2023',
    check_out: '06/08/2023',
    special_request: 'Torres Airport',
    room_type: 'Single Bed',
    room_number: 181,
    status: 'Occupied',
    price: 1511,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '31-419-9508',
    order_date: '31/08/2022',
    check_in: '23/06/2023',
    check_out: '30/06/2023',
    special_request: null,
    room_type: 'Single Bed',
    room_number: 36,
    status: 'Occupied',
    price: 852,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '64-597-4465',
    order_date: '27/02/2022',
    check_in: '27/03/2023',
    check_out: '26/06/2023',
    special_request: 'Rouen Airport',
    room_type: 'Single Bed',
    room_number: 207,
    status: 'Occupied',
    price: 3587,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '29-802-4349',
    order_date: '28/07/2022',
    check_in: '09/11/2023',
    check_out: '29/01/2024',
    special_request: 'Awaba Airport',
    room_type: 'Double Bed',
    room_number: 33,
    status: 'Occupied',
    price: 2597,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '56-561-0700',
    order_date: '08/05/2022',
    check_in: '17/02/2023',
    check_out: '30/05/2023',
    special_request: 'Hultsfred Airport',
    room_type: 'Double Bed',
    room_number: 36,
    status: 'Occupied',
    price: 2689,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '71-183-6345',
    order_date: '09/09/2022',
    check_in: '22/01/2024',
    check_out: '29/01/2024',
    special_request: 'Tanah Merah Airport',
    room_type: 'Double Bed',
    room_number: 188,
    status: 'Occupied',
    price: 350,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '49-754-7669',
    order_date: '16/04/2022',
    check_in: '12/11/2023',
    check_out: '06/12/2023',
    special_request: 'Bomar Field Shelbyville Municipal Airport',
    room_type: 'Double Bed',
    room_number: 233,
    status: 'Occupied',
    price: 1258,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '16-713-6352',
    order_date: '06/07/2022',
    check_in: '27/05/2023',
    check_out: '31/05/2023',
    special_request: null,
    room_type: 'Double Bed',
    room_number: 182,
    status: 'Occupied',
    price: 654,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.food(),
    imageThree: faker.image.nightlife(),
    id: '03-171-4776',
    order_date: '21/02/2022',
    check_in: '06/08/2023',
    check_out: '05/09/2023',
    special_request: 'Maningrida Airport',
    room_type: 'Double Bed',
    room_number: 10,
    status: 'Occupied',
    price: 1500,
  },
  {
    full__name: faker.name.fullName(),
    image: faker.image.avatar(),
    imageTwo: faker.image.avatar(),
    imageThree: faker.image.avatar(),
    id: '44-075-0666',
    order_date: '18/02/2022',
    check_in: '22/05/2023',
    check_out: '04/06/2023',
    special_request: 'Abemama Atoll Airport',
    room_type: 'Double Bed',
    room_number: 8,
    status: 'Occupied',
    price: 1587,
  }
];
