/* eslint-disable prettier/prettier */
import {faker} from '@faker-js/faker';
import room1 from '../assets/images/Room1.jpg';
import room from '../assets/images/Room2.jpg';
import { RoomDataExtended } from '../Interfaces/RoomsDataInterface'; 

export const roomData: RoomDataExtended[] = [
  {
    image: room1,
    id: "1",
    room_number: 112,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: "2",
    room_number: 241,
    room_type: 'Double Bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: faker.commerce.price(100, 2500, 0),   
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0),
    status: 'Occupied',
  },
  {
    image: room1,
    id: "3",
    room_number: 200,
    room_type: 'Double Bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 50,
    offer_price: faker.commerce.price(80, 2200, 0),
    status: 'Occupied',
  },
  {
    image: room1,
    id:"4",
    room_number: 92,
    room_type: 'Suite',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 20,
    offer_price: faker.commerce.price(80, 2200, 0),
    status: 'Occupied',
  },
  {
    image: room1,
    id: "5",
    room_number: 139,
    room_type: 'Double Bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id:"6",
    room_number: 116,
    room_type: 'Double Superior',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id:"7",
    room_number: 176,
    room_type: 'Double Superior',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: null,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id:"8",
    room_number: 202,
    room_type: 'Double Superior',
    name: 'Deluxe A-91254',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: null,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: "9",
    room_number: 82,
    room_type: 'Double Superior',
    name: 'Deluxe A-91254',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: null,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id:"10",
    room_number: 23,
    room_type: 'Single Bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: "11",
    room_number: 88,
    room_type: 'Double Bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: "12",
    room_number: 148,
    room_type: 'Double Bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: null,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: "13",
    room_number: 60,
    room_type: 'Double Bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "Yes",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: "14",
    room_number: 178,
    room_type: 'Double Bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id:"15",
    room_number: 70,
    room_type: 'Suite',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: 10,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: "16",
    room_number: 81,
    room_type: 'Suite',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels"],
    price: faker.commerce.price(100, 2500, 0),
    discount: "No",
    discountPercent: null,
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  }
];
