/* eslint-disable prettier/prettier */
import {faker} from '@faker-js/faker';
import room1 from '../assets/images/Room1.jpg';
import room from '../assets/images/Room2.jpg';
import { RoomDataExtended } from '../store/features/RoomsSlice';

export const roomData: RoomDataExtended[] = [
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 112,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 241,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 200,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 92,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 139,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 116,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 176,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 202,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 82,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 23,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 88,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 148,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 60,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 178,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 70,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 81,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 247,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 87,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 74,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 199,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 16,
    room_type: 'Double bed',
    name: 'Deluxe A-91274',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 237,
    room_type: 'Double bed',
    name: 'Deluxe A-91284',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi"],
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 68,
    room_type: 'Double bed',
    name: 'Deluxe A-91284',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi","Single Bed"],   
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 43,
    room_type: 'Double bed',
    name: 'Deluxe A-91284',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 184,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 104,
    room_type: 'Double bed',
    name: 'Deluxe A-91284',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 208,
    room_type: 'Double bed',
    name: 'Deluxe A-91284',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 82,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 156,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: [ "Breakfast","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 244,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: [ "Breakfast","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 193,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: [ "Breakfast","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 2,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 150,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 207,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Occupied',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 131,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 182,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 89,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 133,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Recreational activities", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 41,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 227,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 129,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 198,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 2,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 202,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 117,
    room_type: 'Double bed',
    name: 'Deluxe A-91294',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Single Bed"],  
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 6,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 111,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 202,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 150,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Electronic Safe / Locker", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 239,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 65,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 243,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 193,
    room_type: 'Double bed',
    name: 'Deluxe A-91224',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 195,
    room_type: 'Double bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking", "Towels","High speed WiFi","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 244,
    room_type: 'Double bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 1,
    room_type: 'Single Bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 142,
    room_type: 'Single Bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 91,
    room_type: 'Single Bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking","Kitchen"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 162,
    room_type: 'Single Bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 116,
    room_type: 'Single Bed',
    name: 'Deluxe A-91264',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 159,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 149,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 195,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 30,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 194,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 134,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 221,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Bath Rob","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 189,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 237,
    room_type: 'Single Bed',
    name: 'Deluxe A-91244',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room1,
    id: faker.random.numeric(5),
    room_number: 114,
    room_type: 'Single Bed',
    name: 'Deluxe A-91241',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 167,
    room_type: 'Single Bed',
    name: 'Deluxe A-91241',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking",  "Mini Bar / Mini Fridge"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 134,
    room_type: 'Single Bed',
    name: 'Deluxe A-91241',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking","Mini Bar / Mini Fridge", "Electronic Safe / Locker"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 176,
    room_type: 'Single Bed',
    name: 'Deluxe A-91241',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking","Mini Bar / Mini Fridge", "Electronic Safe / Locker"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 32,
    room_type: 'Single Bed',
    name: 'Deluxe A-91241',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking","Mini Bar / Mini Fridge", "Electronic Safe / Locker"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
  {
    image: room,
    id: faker.random.numeric(5),
    room_number: 45,
    room_type: 'Single Bed',
    name: 'Deluxe A-91241',
    amenities: ["Air Conditioner","Swimming pool","Beach Towels","Parking","Mini Bar / Mini Fridge", "Electronic Safe / Locker"], 
    price: faker.commerce.price(100, 2500, 0),
    offer_price: faker.commerce.price(80, 2200, 0, ),
    status: 'Available',
  },
];
